import cgi

form = cgi.FieldStorage()

fName = form.getvalue('firstName')
lName = form.getvalue('lastName')
school = form.getvalue('school')


print("Content-Type: text/html\n\n")
print("<html>")
print("<head>")
print("<style>")
print("table, th, td {border: 1px solid black;}")
print("</style>")
print("<title>PHP to Python</title>")
print("</head>")
print("<body>")
print("<h1>WDV 495 Assignment: PHP to Python Form Handler</h1>")
print("<h2>Form Results</h2>")
print("<table><tr><th>First Name</th><th>Last Name</th><th>School</th></tr>")
print("<tr>")
print("<td>")
print((fName))
print("</td>")
print("<td>")
print((lName))
print("</td>")
print("<td>")
print((school))
print("</td>")
print("</tr>")
print("</table>")
print("</body>")
print("</html>")
